@TmsApi_HostAddress = http://localhost:5178

GET {{TmsApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{TmsApi_HostAddress}}/api/assessments/results/
Accept: application/json
###
GET {{TmsApi_HostAddress}}/api/assessments/results1/
X-Training-User: sami
Accept: application/json
###
GET {{TmsApi_HostAddress}}/api/enrollments/worker-smoke/
Accept: application/json
###
GET {{TmsApi_HostAddress}}/payment-options/
Accept: application/json
###
GET {{TmsApi_HostAddress}}/api/enrollments/
Accept: application/json
###

post {{TmsApi_HostAddress}}/api/enrollments/{2}
Accept: application/json
###

curl -X POST http://localhost:5178/api/enrollments \
-H "Content-Type: application/json" \
-d '{"studentId":"S-007","courseCode":"CS-109"}'
###
curl  http://localhost:5178/api/enrollments/
###

curl -X DELETE http://localhost:5178/api/enrollments/a4257ea7
###
GET http://localhost:5178/api/error 
Accept: application/json
###
GET http://localhost:5178/scalar/v1 
Accept: application/json
###
GET http://localhost:5178/api/courses
###
GET http://localhost:5178/api/students
###
GET http://localhost:5178/api/enrollments
###
GET   http://localhost:5178/api/courses/CS-101

###
curl http://localhost:5178/api/test/deferred
###
curl http://localhost:5178/api/test/translation-fail

###
curl http://localhost:5178/api/reports/active-students
###
get http://localhost:5178/api/reports/course-enrollments
###
get http://localhost:5178/api/reports/average-gpa
###
Get http://localhost:5178/api/reports/students-no-enrollment-b
###
Get http://localhost:5178/api/students/small-page-response
###
get http://localhost:5178/api/students/small-page-response?pageNumber=1
###
GET   http://localhost:5178/api/courses/top-5-courses

###
put http://localhost:5178/api/students/1
Content-Type: application/json
###
DELETE http://localhost:5178/api/enrollments/7e960cf4
Content-Type: application/json
###

curl -X PUT http://localhost:5178/api/enrollments/2/archive
###
curl -X POST http://localhost:5178/api/courses
-H "Content-Type: application/json" \
-d '{ "code": "CSE-101",
"title": "Web
Development
Fundamentals",
"maxCapacity": 30 }'
###
curl -X POST  http://localhost:5178/api/courses
-H "Content-Type: application/json" \
-d '{
"code": "CSE-113",
"title": "operating systems",
"studentId": "S-007",
"MaxCapacity": 1 }'

 
 
